import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import p1 from '../../../../public/p1.png';
import p2 from '../../../../public/p2.png';
import p3 from '../../../../public/p3.png';
import p5 from '../../../../public/p5.png';


function projects() {
  return (
    <div data-aos="fade-up" className='project-div custom-xl:my-[60px] custom-xl:px-[40px]         custom-lg:my-[60px] custom-lg:px-[40px]       custom-md:my-[60px] custom-md:px-[40px]       custom-sm:my-[60px] custom-sm:px-[20px]         custom-xs:my-[60px] custom-xs:px-[20px]            custom-xxs:my-[70px] custom-xxs:px-[5px]            custom-tiny:my-[50px] custom-tiny:px-[5px]            custom-mini:my-[50px] custom-mini:px-[5px] '>

    <div className='justify-items-center text-white text-[32px] font-bold'>
    <h1 data-aos="fade-up" className='project-heading'>Projects</h1>
    </div>

    <div className='custom-xl:my-[60px] custom-xl:mx-[40px]       items-center  custom-lg:my-[60px] custom-lg:mx-[40px]         custom-md:my-[60px] custom-md:mx-[10px]         custom-sm:my-[60px] custom-sm:mx-[70px]          custom-xs:my-[60px] custom-xs:mx-[60px]                 custom-xxs:my-[60px] custom-xxs:mx-[30px]         custom-tiny:my-[50px] custom-tiny:mx-[30px]          custom-mini:my-[50px] custom-mini:mx-[20px]     custom-xl:justify-items-center custom-lg:justify-items-center custom-md:justify-items-center custom-sm:justify-items-center custom-xs:justify-items-left custom-xxs:justify-items-left custom-tiny:justify-items-left custom-mini:justify-items-left '>

      <div data-aos="fade-up" className='project-one         custom-xl:mb-[100px] custom-xl:flex custom-xl:gap-[40px]           custom-lg:mb-[100px] custom-lg:flex custom-lg:gap-[30px]           custom-md:mb-[100px] custom-md:flex custom-md:gap-[30px]            custom-sm:mb-[100px] custom-sm:block custom-sm:gap-[30px]            custom-xs:mb-[100px] custom-xs:block custom-xs:gap-[30px]             custom-xxs:mb-[100px] custom-xxs:block custom-xxs:gap-[30px]             custom-tiny:mb-[100px] custom-tiny:block custom-tiny:gap-[20px]             custom-mini:mb-[50px] custom-mini:block custom-mini:gap-[0px] '>
        <div data-aos="fade-up" className='projects-content-one'>
        <h3 className='project-one-h text-white font-bold mb-4      custom-xl:text-[19px]       custom-lg:text-[19px]       custom-md:text-[19px]        custom-sm:text-[19px]        custom-xs:text-[19px]        custom-xxs:text-[19px]        custom-tiny:text-[18px]        custom-mini:text-[17px] '>GIAIC Website Clone Project</h3>
        <div className='project-one-content-div      bg-[#1b1532c1] rounded-[10px]                custom-xl:py-[30px] custom-xl:px-[20px] custom-xl:h-[130px] custom-xl:w-[500px] custom-xl:text-[16px]              custom-lg:py-[30px] custom-lg:px-[20px] custom-lg:h-[150px] custom-lg:w-[500px] custom-lg:text-[15px]               custom-md:py-[25px] custom-md:px-[15px] custom-md:h-[130px] custom-md:w-[400px] custom-md:text-[14px]                custom-sm:py-[25px] custom-sm:px-[20px] custom-sm:h-[130px] custom-sm:w-[600px] custom-sm:text-base custom-sm:mb-[20px]                custom-xs:py-[30px] custom-xs:px-[20px] custom-xs:h-[145px] custom-xs:w-[500px] custom-xs:text-base custom-xs:mb-[20px]                custom-xxs:py-[30px] custom-xxs:px-[25px] custom-xxs:h-[150px] custom-xxs:w-[400px] custom-xxs:text-[6px] custom-xxs:mb-[20px]                custom-tiny:py-[15px] custom-tiny:px-[25px] custom-tiny:h-[130px] custom-tiny:w-[300px] custom-tiny:text-[9px] custom-tiny:mb-[20px]                custom-mini:py-[20px] custom-mini:px-[20px] custom-mini:h-[140px] custom-mini:w-[260px] custom-mini:text-[9px] custom-mini:mb-[20px]'> 
        <p className='project-one-p text-[#d8cde8]    mb-3 leading-none custom-xl:text-base   custom-lg:text-[15px] custom-md:text-[13px] custom-sm:text-[15px] custom-xs:text-[15px] custom-xxs:text-[15px] custom-tiny:text-[13px] custom-mini:text-[13px]'>Developed a responsive clone of the Governor of Sindh&apos;s website using Tailwind CSS and TypeScript, focusing on clean design and cross-device functionality</p>
          <div>
          <Link  href='https://giaic-website-three.vercel.app/'>
            <button className='project-btn  bg-[#ad6bf1] border-[#ad6bf1] text-white rounded-[5px]          custom-xl:text-[12px] custom-xl:py-[5.50px] custom-xl:px-0 custom-xl:w-[95px]          custom-lg:text-[12px] custom-lg:py-[5px] custom-lg:px-0 custom-lg:w-[95px]              custom-md:text-[12px] custom-md:py-[5px] custom-md:px-0 custom-md:w-[95px]          custom-sm:text-[12px] custom-sm:py-[4px] custom-sm:px-0 custom-sm:w-[100px]          custom-xs:text-[12px] custom-xs:py-[4px] custom-xs:px-0 custom-xs:w-[95px]          custom-xxs:text-[12px] custom-xxs:py-[4px] custom-xxs:px-0 custom-xxs:w-[95px]          custom-tiny:text-[12px] custom-tiny:py-[5px] custom-tiny:px-0 custom-tiny:w-[95px]          custom-mini:text-[11px] custom-mini:py-[4px] custom-mini:px-0 custom-mini:w-[90px] h-[26px]'>View My Project</button>
          </Link>
          </div>
        </div>
        </div>
        <div>
        <Image data-aos="fade-up" className='project-one-img  rounded-[10px] shadow-[#31145aac]     custom-xl:block custom-xl:shadow-[10px]    custom-lg:block custom-lg:shadow-[10px]      custom-md:block custom-md:shadow-[8px]      custom-sm:hidden custom-sm:shadow-[8px]       custom-xs:hidden custom-xs:shadow-[8px]        custom-xxs:hidden custom-xxs:shadow-[8px]         custom-tiny:hidden custom-tiny:shadow-[8px]         custom-mini:hidden custom-mini:shadow-[8px] ' alt='img' src={p1}/>
        </div>
      </div>

      <div data-aos="fade-up" className='project-two         custom-xl:mb-[100px] custom-xl:flex custom-xl:gap-[40px]           custom-lg:mb-[100px] custom-lg:flex custom-lg:gap-[30px]           custom-md:mb-[100px] custom-md:flex custom-md:gap-[30px]            custom-sm:mb-[100px] custom-sm:block custom-sm:gap-[30px]            custom-xs:mb-[100px] custom-xs:block custom-xs:gap-[30px]             custom-xxs:mb-[100px] custom-xxs:block custom-xxs:gap-[30px]             custom-tiny:mb-[100px] custom-tiny:block custom-tiny:gap-[20px]             custom-mini:mb-[50px] custom-mini:block custom-mini:gap-[0px] '>
      <div>
          <Image data-aos="fade-up" className='project-two-img  rounded-[10px] shadow-[#31145aac]     custom-xl:block custom-xl:shadow-[10px]      custom-lg:block custom-lg:shadow-[10px]      custom-md:block custom-md:shadow-[8px]      custom-sm:hidden custom-sm:shadow-[8px]       custom-xs:hidden custom-xs:shadow-[8px]        custom-xxs:hidden custom-xxs:shadow-[8px]         custom-tiny:hidden custom-tiny:shadow-[8px]         custom-mini:hidden custom-mini:shadow-[8px] ' alt='img' src={p2}/>
        </div>
        <div data-aos="fade-up" className='projects-content-two'>
        <h3 className='project-two-h text-white font-bold mb-3       custom-xl:text-[20.8px]       custom-lg:text-[20.8px]       custom-md:text-[19px]        custom-sm:text-[19px]        custom-xs:text-[19px]        custom-xxs:text-[19px]        custom-tiny:text-[18px]        custom-mini:text-[17px] '>Storm Safe Website Project</h3>
        <div className='project-two-content-div      bg-[#1b1532c1] rounded-[10px]                custom-xl:py-[30px] custom-xl:px-[20px] custom-xl:h-[130px] custom-xl:w-[500px] custom-xl:text-[16px]              custom-lg:py-[30px] custom-lg:px-[20px] custom-lg:h-[150px] custom-lg:w-[500px] custom-lg:text-[15px]               custom-md:py-[25px] custom-md:px-[15px] custom-md:h-[130px] custom-md:w-[400px] custom-md:text-[14px]                custom-sm:py-[25px] custom-sm:px-[20px] custom-sm:h-[130px] custom-sm:w-[600px] custom-sm:text-base custom-sm:mb-[20px]                custom-xs:py-[30px] custom-xs:px-[20px] custom-xs:h-[145px] custom-xs:w-[500px] custom-xs:text-base custom-xs:mb-[20px]                custom-xxs:py-[30px] custom-xxs:px-[25px] custom-xxs:h-[150px] custom-xxs:w-[400px] custom-xxs:text-[6px] custom-xxs:mb-[20px]                custom-tiny:py-[15px] custom-tiny:px-[25px] custom-tiny:h-[130px] custom-tiny:w-[300px] custom-tiny:text-[9px] custom-tiny:mb-[20px]                custom-mini:py-[20px] custom-mini:px-[20px] custom-mini:h-[140px] custom-mini:w-[260px] custom-mini:text-[9px] custom-mini:mb-[20px]'>
        <p className='project-two-p text-[#d8cde8]    mb-3 leading-none custom-xl:text-base   custom-lg:text-[15px] custom-md:text-[13px] custom-sm:text-[15px] custom-xs:text-[15px] custom-xxs:text-[15px] custom-tiny:text-[13px] custom-mini:text-[13px]'>Created a comprehensive hurricane information website with responsive design. Features include real-time updates, safety tips, historical data, and emergency resources.</p>
          <div>
          <Link href='https://storm-safe-site.vercel.app/'>
          <button className='project-btn  bg-[#ad6bf1] border-[#ad6bf1] text-white rounded-[5px]          custom-xl:text-[12px] custom-xl:py-[5.50px] custom-xl:px-0 custom-xl:w-[95px]          custom-lg:text-[12px] custom-lg:py-[5px] custom-lg:px-0 custom-lg:w-[95px]              custom-md:text-[12px] custom-md:py-[5px] custom-md:px-0 custom-md:w-[95px]          custom-sm:text-[12px] custom-sm:py-[4px] custom-sm:px-0 custom-sm:w-[100px]          custom-xs:text-[12px] custom-xs:py-[4px] custom-xs:px-0 custom-xs:w-[95px]          custom-xxs:text-[12px] custom-xxs:py-[4px] custom-xxs:px-0 custom-xxs:w-[95px]          custom-tiny:text-[12px] custom-tiny:py-[5px] custom-tiny:px-0 custom-tiny:w-[95px]          custom-mini:text-[11px] custom-mini:py-[4px] custom-mini:px-0 custom-mini:w-[90px] h-[26px]'>View My Project</button>
          </Link>
          </div>
        </div>
        </div>
      </div>

      <div data-aos="fade-up" className='project-one          custom-xl:mb-[100px] custom-xl:flex custom-xl:gap-[40px]           custom-lg:mb-[100px] custom-lg:flex custom-lg:gap-[30px]           custom-md:mb-[100px] custom-md:flex custom-md:gap-[30px]            custom-sm:mb-[100px] custom-sm:block custom-sm:gap-[30px]            custom-xs:mb-[100px] custom-xs:block custom-xs:gap-[30px]             custom-xxs:mb-[100px] custom-xxs:block custom-xxs:gap-[30px]             custom-tiny:mb-[100px] custom-tiny:block custom-tiny:gap-[20px]             custom-mini:mb-[50px] custom-mini:block custom-mini:gap-[0px] '>
      <div className='projects-content-one'>
        <h3 className='project-one-h text-white font-bold mb-4      custom-xl:text-[19px]       custom-lg:text-[19px]       custom-md:text-[19px]        custom-sm:text-[19px]        custom-xs:text-[19px]        custom-xxs:text-[19px]        custom-tiny:text-[18px]        custom-mini:text-[17px] '>Editable Resume Generator Project</h3>
        <div className='project-one-content-div       bg-[#1b1532c1] rounded-[10px]                custom-xl:py-[30px] custom-xl:px-[20px] custom-xl:h-[130px] custom-xl:w-[500px] custom-xl:text-[16px]              custom-lg:py-[30px] custom-lg:px-[20px] custom-lg:h-[150px] custom-lg:w-[500px] custom-lg:text-[15px]               custom-md:py-[25px] custom-md:px-[15px] custom-md:h-[130px] custom-md:w-[400px] custom-md:text-[14px]                custom-sm:py-[25px] custom-sm:px-[20px] custom-sm:h-[130px] custom-sm:w-[600px] custom-sm:text-base custom-sm:mb-[20px]                custom-xs:py-[30px] custom-xs:px-[20px] custom-xs:h-[145px] custom-xs:w-[500px] custom-xs:text-base custom-xs:mb-[20px]                custom-xxs:py-[30px] custom-xxs:px-[25px] custom-xxs:h-[150px] custom-xxs:w-[400px] custom-xxs:text-[6px] custom-xxs:mb-[20px]                custom-tiny:py-[15px] custom-tiny:px-[25px] custom-tiny:h-[130px] custom-tiny:w-[300px] custom-tiny:text-[9px] custom-tiny:mb-[20px]                custom-mini:py-[20px] custom-mini:px-[20px] custom-mini:h-[140px] custom-mini:w-[260px] custom-mini:text-[9px] custom-mini:mb-[20px]'>  
        <p className='project-one-p text-[#d8cde8]    mb-3 leading-none custom-xl:text-base   custom-lg:text-[15px] custom-md:text-[13px] custom-sm:text-[15px] custom-xs:text-[15px] custom-xxs:text-[15px] custom-tiny:text-[13px] custom-mini:text-[13px]'>Developed a dynamic resume builder using HTML, CSS, and TypeScript, featuring a user-friendly interface for real-time resume generation based on user input.</p>
          <div>
          <Link href='https://editable-resume-ten-phi.vercel.app/'>
          <button className='project-btn   bg-[#ad6bf1] border-[#ad6bf1] text-white rounded-[5px]          custom-xl:text-[12px] custom-xl:py-[5.50px] custom-xl:px-0 custom-xl:w-[95px]          custom-lg:text-[12px] custom-lg:py-[5px] custom-lg:px-0 custom-lg:w-[95px]              custom-md:text-[12px] custom-md:py-[5px] custom-md:px-0 custom-md:w-[95px]          custom-sm:text-[12px] custom-sm:py-[4px] custom-sm:px-0 custom-sm:w-[100px]          custom-xs:text-[12px] custom-xs:py-[4px] custom-xs:px-0 custom-xs:w-[95px]          custom-xxs:text-[12px] custom-xxs:py-[4px] custom-xxs:px-0 custom-xxs:w-[95px]          custom-tiny:text-[12px] custom-tiny:py-[5px] custom-tiny:px-0 custom-tiny:w-[95px]          custom-mini:text-[11px] custom-mini:py-[4px] custom-mini:px-0 custom-mini:w-[90px] h-[26px]'>View My Project</button>
          </Link>
          </div>
        </div>
        </div>
        <div>
        <Image data-aos="fade-up" className='project-one-img   rounded-[10px] shadow-[#31145aac]     custom-xl:block custom-xl:shadow-[10px]      custom-lg:block custom-lg:shadow-[10px]      custom-md:block custom-md:shadow-[8px]      custom-sm:hidden custom-sm:shadow-[8px]       custom-xs:hidden custom-xs:shadow-[8px]        custom-xxs:hidden custom-xxs:shadow-[8px]         custom-tiny:hidden custom-tiny:shadow-[8px]         custom-mini:hidden custom-mini:shadow-[8px] ' alt='img' src={p3}/>
        </div>
      </div>

      <div data-aos="fade-up" className='project-two         custom-xl:mb-[100px] custom-xl:flex custom-xl:gap-[40px]           custom-lg:mb-[100px] custom-lg:flex custom-lg:gap-[30px]           custom-md:mb-[100px] custom-md:flex custom-md:gap-[30px]            custom-sm:mb-[100px] custom-sm:block custom-sm:gap-[30px]            custom-xs:mb-[100px] custom-xs:block custom-xs:gap-[30px]             custom-xxs:mb-[100px] custom-xxs:block custom-xxs:gap-[30px]             custom-tiny:mb-[100px] custom-tiny:block custom-tiny:gap-[20px]             custom-mini:mb-[50px] custom-mini:block custom-mini:gap-[0px] '>
      <div>
        <Image data-aos="fade-up" className='project-two-img  rounded-[10px] shadow-[#31145aac]     custom-xl:block custom-xl:shadow-[10px]      custom-lg:block custom-lg:shadow-[10px]      custom-md:block custom-md:shadow-[8px]      custom-sm:hidden custom-sm:shadow-[8px]       custom-xs:hidden custom-xs:shadow-[8px]        custom-xxs:hidden custom-xxs:shadow-[8px]         custom-tiny:hidden custom-tiny:shadow-[8px]         custom-mini:hidden custom-mini:shadow-[8px] ' alt='img' src={p3}/>
        </div>
        <div className='projects-content-two'>
        <h3 data-aos="fade-up" className='project-two-h text-white font-bold mb-4      custom-xl:text-[19px]       custom-lg:text-[19px]       custom-md:text-[19px]        custom-sm:text-[19px]        custom-xs:text-[19px]        custom-xxs:text-[19px]        custom-tiny:text-[18px]        custom-mini:text-[17px] '>Dynamic Resume Generator Project</h3>
        <div className='project-two-content-div       bg-[#1b1532c1] rounded-[10px]                custom-xl:py-[30px] custom-xl:px-[20px] custom-xl:h-[130px] custom-xl:w-[500px] custom-xl:text-[16px]              custom-lg:py-[30px] custom-lg:px-[20px] custom-lg:h-[150px] custom-lg:w-[500px] custom-lg:text-[15px]               custom-md:py-[25px] custom-md:px-[15px] custom-md:h-[130px] custom-md:w-[400px] custom-md:text-[14px]                custom-sm:py-[25px] custom-sm:px-[20px] custom-sm:h-[130px] custom-sm:w-[600px] custom-sm:text-base custom-sm:mb-[20px]                custom-xs:py-[30px] custom-xs:px-[20px] custom-xs:h-[145px] custom-xs:w-[500px] custom-xs:text-base custom-xs:mb-[20px]                custom-xxs:py-[30px] custom-xxs:px-[25px] custom-xxs:h-[150px] custom-xxs:w-[400px] custom-xxs:text-[6px] custom-xxs:mb-[20px]                custom-tiny:py-[15px] custom-tiny:px-[25px] custom-tiny:h-[130px] custom-tiny:w-[300px] custom-tiny:text-[9px] custom-tiny:mb-[20px]                custom-mini:py-[20px] custom-mini:px-[20px] custom-mini:h-[140px] custom-mini:w-[260px] custom-mini:text-[9px] custom-mini:mb-[20px]'>  
        <p className='project-two-p text-[#d8cde8]    mb-3 leading-none custom-xl:text-base   custom-lg:text-[15px] custom-md:text-[13px] custom-sm:text-[15px] custom-xs:text-[15px] custom-xxs:text-[15px] custom-tiny:text-[13px] custom-mini:text-[13px]'>Created a dynamic resume builder using HTML, CSS, and TypeScript, offering a user-friendly interface for real-time resume customization and generation.</p>
          <div>
          <Link href='https://dynamic-resume-builder-rho-ruddy.vercel.app/'>
          <button className='project-btn  bg-[#ad6bf1] border-[#ad6bf1] text-white rounded-[5px]          custom-xl:text-[12px] custom-xl:py-[5.50px] custom-xl:px-0 custom-xl:w-[95px]          custom-lg:text-[12px] custom-lg:py-[5px] custom-lg:px-0 custom-lg:w-[95px]              custom-md:text-[12px] custom-md:py-[5px] custom-md:px-0 custom-md:w-[95px]          custom-sm:text-[12px] custom-sm:py-[4px] custom-sm:px-0 custom-sm:w-[100px]          custom-xs:text-[12px] custom-xs:py-[4px] custom-xs:px-0 custom-xs:w-[95px]          custom-xxs:text-[12px] custom-xxs:py-[4px] custom-xxs:px-0 custom-xxs:w-[95px]          custom-tiny:text-[12px] custom-tiny:py-[5px] custom-tiny:px-0 custom-tiny:w-[95px]          custom-mini:text-[11px] custom-mini:py-[4px] custom-mini:px-0 custom-mini:w-[90px] h-[26px]'>View My Project</button>
          </Link>
          </div>
        </div>
        </div>
      </div>
      
      <div data-aos="fade-up" className='project-one          custom-xl:mb-[100px] custom-xl:flex custom-xl:gap-[40px]           custom-lg:mb-[100px] custom-lg:flex custom-lg:gap-[30px]           custom-md:mb-[100px] custom-md:flex custom-md:gap-[30px]            custom-sm:mb-[100px] custom-sm:block custom-sm:gap-[30px]            custom-xs:mb-[100px] custom-xs:block custom-xs:gap-[30px]             custom-xxs:mb-[100px] custom-xxs:block custom-xxs:gap-[30px]             custom-tiny:mb-[100px] custom-tiny:block custom-tiny:gap-[20px]             custom-mini:mb-[50px] custom-mini:block custom-mini:gap-[0px] '>
      <div data-aos="fade-up" className='projects-content-one'>
        <h3 className='project-one-h text-white font-bold mb-4      custom-xl:text-[19px]       custom-lg:text-[19px]       custom-md:text-[19px]        custom-sm:text-[19px]        custom-xs:text-[19px]        custom-xxs:text-[19px]        custom-tiny:text-[18px]        custom-mini:text-[17px] '>PanaCloud Website Clone Project</h3>
        <div className='project-one-content-div      bg-[#1b1532c1] rounded-[10px]                custom-xl:py-[30px] custom-xl:px-[20px] custom-xl:h-[130px] custom-xl:w-[500px] custom-xl:text-[16px]              custom-lg:py-[30px] custom-lg:px-[20px] custom-lg:h-[150px] custom-lg:w-[500px] custom-lg:text-[15px]               custom-md:py-[25px] custom-md:px-[15px] custom-md:h-[130px] custom-md:w-[400px] custom-md:text-[14px]                custom-sm:py-[25px] custom-sm:px-[20px] custom-sm:h-[130px] custom-sm:w-[600px] custom-sm:text-base custom-sm:mb-[20px]                custom-xs:py-[30px] custom-xs:px-[20px] custom-xs:h-[145px] custom-xs:w-[500px] custom-xs:text-base custom-xs:mb-[20px]                custom-xxs:py-[30px] custom-xxs:px-[25px] custom-xxs:h-[150px] custom-xxs:w-[400px] custom-xxs:text-[6px] custom-xxs:mb-[20px]                custom-tiny:py-[15px] custom-tiny:px-[25px] custom-tiny:h-[130px] custom-tiny:w-[300px] custom-tiny:text-[9px] custom-tiny:mb-[20px]                custom-mini:py-[20px] custom-mini:px-[20px] custom-mini:h-[140px] custom-mini:w-[260px] custom-mini:text-[9px] custom-mini:mb-[20px]'>  
        <p className='project-one-p text-[#d8cde8]    mb-3 leading-none custom-xl:text-base   custom-lg:text-[15px] custom-md:text-[13px] custom-sm:text-[15px] custom-xs:text-[15px] custom-xxs:text-[15px] custom-tiny:text-[13px] custom-mini:text-[13px]'>Developed a comprehensive website for Pana Cloud, highlighting expertise in web and graphic design, branding, and marketing. The site features client testimonials, a systematic work process, and dedicated support.</p>
          <div>
          <Link href='https://pana-cloud-nextjs.vercel.app/'>
          <button className='project-btn  bg-[#ad6bf1] border-[#ad6bf1] text-white rounded-[5px]          custom-xl:text-[12px] custom-xl:py-[5.50px] custom-xl:px-0 custom-xl:w-[95px]          custom-lg:text-[12px] custom-lg:py-[5px] custom-lg:px-0 custom-lg:w-[95px]              custom-md:text-[12px] custom-md:py-[5px] custom-md:px-0 custom-md:w-[95px]          custom-sm:text-[12px] custom-sm:py-[4px] custom-sm:px-0 custom-sm:w-[100px]          custom-xs:text-[12px] custom-xs:py-[4px] custom-xs:px-0 custom-xs:w-[95px]          custom-xxs:text-[12px] custom-xxs:py-[4px] custom-xxs:px-0 custom-xxs:w-[95px]          custom-tiny:text-[12px] custom-tiny:py-[5px] custom-tiny:px-0 custom-tiny:w-[95px]          custom-mini:text-[11px] custom-mini:py-[4px] custom-mini:px-0 custom-mini:w-[90px] h-[26px]'>View My Project</button>
          </Link>
          </div>
        </div>
        </div>
        <div>
        <Image data-aos="fade-up" className='project-one-img    rounded-[10px] shadow-[#31145aac]     custom-xl:block custom-xl:shadow-[10px]      custom-lg:block custom-lg:shadow-[10px]      custom-md:block custom-md:shadow-[8px]      custom-sm:hidden custom-sm:shadow-[8px]       custom-xs:hidden custom-xs:shadow-[8px]        custom-xxs:hidden custom-xxs:shadow-[8px]         custom-tiny:hidden custom-tiny:shadow-[8px]         custom-mini:hidden custom-mini:shadow-[8px] ' alt='img' src={p5}/>
        </div>
      </div>
    </div>

  </div>
  )
}

export default projects;